# Generated by Django 5.2.6 on 2025-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Soriana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_registro',
            field=models.CharField(choices=[('Local', 'Local'), ('En linea', 'En linea')], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
